const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "+94769872326"
const SESSION_ID = "PRABATH-MD~s3lBWLzY#Vn1j1GOEqsgkMDWTNPkMK8iNVfd45PS_MjA-xjwmEZI"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
